# Site settings
title: letslawful
email: "&#104;&#105;&#064;&#112;&#101;&#105;&#119;&#101;&#110;&#046;&#108;&#117;"
description: "letslawful's front-end blog."
baseurl: ""
url: "http://peiwen.lu"
permalink: /:year/:title


# Social account
facebook:  白马
# weibo:    ID
github:   letslawful
codepen:  letslawful
# dribbble: username


# Comment
# disqus_shortname:


# Google Analytics
google_analytics: UA-60830414-1


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
