# Site settings
title: 老夫的自留地
email: "letslawfull@gmail.com"
description: "“天空没有留下痕迹，飞鸟已从这里飞过。”但是我想留下属于我的痕迹。"
baseurl: ""
url: "https://letslawful.github.io"
permalink: /:year/:title


# Social account
facebook:  白马
# weibo:    ID
github:   letslawful
codepen:  letslawful
# dribbble: username


# Comment
# disqus_shortname:


# Google Analytics
google_analytics: UA-60830414-1


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
