# Site settings
title: letslawful
email: "letslawfull@gmail.com"
description: "letslawful's front-end blog."
baseurl: ""
url: "https://letslawful.github.io"
permalink: /:year/:title


# Social account
facebook:  白马
# weibo:    ID
github:   letslawful
codepen:  letslawful
# dribbble: username


# Comment
# disqus_shortname:


# Google Analytics
google_analytics: UA-60830414-1


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
